#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12.1.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'bird.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/12.1.1
if [ -x "/etc/init.d/bird" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native bird stop || exit 1
fi
# End automatically added section
